version: '3.8'

services:
  web:
    build: .
    ports:
      - "9876:9876"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=9876
