version: '3.8'

services:
  web:
    build: .
    ports:
      - "9876:9876"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
    entrypoint: ["/entrypoint.sh"]

  test:
    build: .
    command: ["pytest"]
    volumes:
      - .:/app

  code-quality:
    build: .
    command: ["code-quality"]
    volumes:
      - .:/app
